const fs = require('fs');

const exercises = [
  'Brisk Walking', 'Gentle Yoga', 'Swimming', 'Chair Aerobics',
  'Resistance Band Training', 'Tai Chi', 'Bodyweight Squats',
  'Stretching Routine', 'Dancing', 'Pilates', 'Heavy Lifting'
];

let achievements = [];
let logic = [];

function addAchievement(id, name, desc, icon, condition) {
  achievements.push(`  { id: '${id}', name: '${name.replace(/'/g, "\\'")}', description: '${desc.replace(/'/g, "\\'")}', icon: '${icon}' }`);
  logic.push(`  if (${condition}) unlocked.push(achMap['${id}']);`);
}

// 1. Total Count (10)
const counts = [1, 5, 10, 25, 50, 100, 250, 500, 1000, 2000];
counts.forEach(c => addAchievement(`count_${c}`, `Activity Level ${c}`, `Log ${c} total activities`, 'Star', `count >= ${c}`));

// 2. Active Minutes (10)
const mins = [50, 100, 500, 1000, 2500, 5000, 10000, 25000, 50000, 100000];
mins.forEach(m => addAchievement(`min_${m}`, `Time Master ${m}`, `Reach ${m} active minutes`, 'Award', `dur >= ${m}`));

// 3. Unique Exercises (5)
const uniques = [3, 5, 10, 15, 20];
uniques.forEach(u => addAchievement(`unique_${u}`, `Variety Pack ${u}`, `Log ${u} different types of exercises`, 'Medal', `uniqueExercises >= ${u}`));

// 4. Longest Session (6)
const sessions = [60, 90, 120, 180, 240, 300];
sessions.forEach(s => addAchievement(`session_${s}`, `Endurance ${s}`, `Log a single activity of ${s}+ minutes`, 'Trophy', `maxSession >= ${s}`));

// 5. Streaks (8)
const streaks = [3, 7, 14, 30, 60, 100, 200, 365];
streaks.forEach(s => addAchievement(`streak_${s}`, `Streak ${s}`, `Log activities ${s} days in a row`, 'Flame', `maxStreak >= ${s}`));

// 6. Specific Exercises (11 * 5 = 55)
const exCounts = [1, 5, 20, 50, 100];
exercises.forEach(ex => {
  exCounts.forEach(c => {
    let safename = ex.toLowerCase().replace(/[^a-z0-9]/g, '_');
    addAchievement(`ex_${safename}_${c}`, `${ex} Fanatic ${c}`, `Log ${ex} ${c} times`, 'Star', `(exerciseCounts['${ex}'] || 0) >= ${c}`);
  });
});

// 7. Weekend Warrior (5)
const weekendCounts = [1, 5, 20, 50, 100];
weekendCounts.forEach(w => addAchievement(`weekend_${w}`, `Weekend Warrior ${w}`, `Log ${w} weekend activities`, 'Medal', `weekendCount >= ${w}`));

// Legacy defaults
addAchievement('first_step', 'First Step', 'Log your first activity', 'Star', 'count >= 1');
addAchievement('getting_serious', 'Getting Serious', 'Log 5 total activities', 'Medal', 'count >= 5');
addAchievement('century_club', 'Century Club', 'Reach 100 active minutes', 'Award', 'dur >= 100');
addAchievement('marathoner', 'Marathoner', 'Reach 500 active minutes', 'Trophy', 'dur >= 500');

const fileContent = `// THIS FILE IS AUTOMATICALLY GENERATED
import { type ActivityLog, type Achievement } from '../api';

export const ALL_ACHIEVEMENTS: Achievement[] = [
${achievements.join(',\n')}
];

const achMap = Object.fromEntries(ALL_ACHIEVEMENTS.map(a => [a.id, a]));

export function evaluateAchievements(logs: ActivityLog[]): Achievement[] {
  const count = logs.length;
  const dur = logs.reduce((sum, doc) => sum + doc.duration, 0);
  const uniqueExercises = new Set(logs.map(l => l.exercise_name)).size;
  const maxSession = logs.reduce((max, l) => Math.max(max, l.duration), 0);
  
  const exerciseCounts: Record<string, number> = {};
  logs.forEach(l => {
    exerciseCounts[l.exercise_name] = (exerciseCounts[l.exercise_name] || 0) + 1;
  });

  const weekendCount = logs.filter(l => {
    const [y, m, d] = l.date.split('-').map(Number);
    const dayOfWeek = new Date(y, m - 1, d).getDay();
    return dayOfWeek === 0 || dayOfWeek === 6;
  }).length;

  const uniqueDates = Array.from(new Set(logs.map(l => l.date))).sort();
  let maxStreak = 0;
  let curStr = 0;
  for (let i = 0; i < uniqueDates.length; i++) {
    if (i === 0) curStr = 1;
    else {
      const [y1, m1, d1] = uniqueDates[i-1].split('-').map(Number);
      const [y2, m2, d2] = uniqueDates[i].split('-').map(Number);
      const diffDays = Math.round((new Date(y2, m2 - 1, d2).getTime() - new Date(y1, m1 - 1, d1).getTime()) / (1000 * 3600 * 24));
      if (diffDays === 1) curStr++;
      else curStr = 1;
    }
    maxStreak = Math.max(maxStreak, curStr);
  }

  const unlocked: Achievement[] = [];
${logic.join('\n')}

  return unlocked;
}
`;

fs.writeFileSync('C:/Users/Dion/Documents/Projects/FitTrack/src/data/achievements.ts', fileContent);
