// THIS FILE IS AUTOMATICALLY GENERATED
import { type ActivityLog, type Achievement } from '../api';

export const ALL_ACHIEVEMENTS: Achievement[] = [
  { id: 'count_1', name: 'Activity Level 1', description: 'Log 1 total activities', icon: 'Star' },
  { id: 'count_5', name: 'Activity Level 5', description: 'Log 5 total activities', icon: 'Star' },
  { id: 'count_10', name: 'Activity Level 10', description: 'Log 10 total activities', icon: 'Star' },
  { id: 'count_25', name: 'Activity Level 25', description: 'Log 25 total activities', icon: 'Star' },
  { id: 'count_50', name: 'Activity Level 50', description: 'Log 50 total activities', icon: 'Star' },
  { id: 'count_100', name: 'Activity Level 100', description: 'Log 100 total activities', icon: 'Star' },
  { id: 'count_250', name: 'Activity Level 250', description: 'Log 250 total activities', icon: 'Star' },
  { id: 'count_500', name: 'Activity Level 500', description: 'Log 500 total activities', icon: 'Star' },
  { id: 'count_1000', name: 'Activity Level 1000', description: 'Log 1000 total activities', icon: 'Star' },
  { id: 'count_2000', name: 'Activity Level 2000', description: 'Log 2000 total activities', icon: 'Star' },
  { id: 'min_50', name: 'Time Master 50', description: 'Reach 50 active minutes', icon: 'Award' },
  { id: 'min_100', name: 'Time Master 100', description: 'Reach 100 active minutes', icon: 'Award' },
  { id: 'min_500', name: 'Time Master 500', description: 'Reach 500 active minutes', icon: 'Award' },
  { id: 'min_1000', name: 'Time Master 1000', description: 'Reach 1000 active minutes', icon: 'Award' },
  { id: 'min_2500', name: 'Time Master 2500', description: 'Reach 2500 active minutes', icon: 'Award' },
  { id: 'min_5000', name: 'Time Master 5000', description: 'Reach 5000 active minutes', icon: 'Award' },
  { id: 'min_10000', name: 'Time Master 10000', description: 'Reach 10000 active minutes', icon: 'Award' },
  { id: 'min_25000', name: 'Time Master 25000', description: 'Reach 25000 active minutes', icon: 'Award' },
  { id: 'min_50000', name: 'Time Master 50000', description: 'Reach 50000 active minutes', icon: 'Award' },
  { id: 'min_100000', name: 'Time Master 100000', description: 'Reach 100000 active minutes', icon: 'Award' },
  { id: 'unique_3', name: 'Variety Pack 3', description: 'Log 3 different types of exercises', icon: 'Medal' },
  { id: 'unique_5', name: 'Variety Pack 5', description: 'Log 5 different types of exercises', icon: 'Medal' },
  { id: 'unique_10', name: 'Variety Pack 10', description: 'Log 10 different types of exercises', icon: 'Medal' },
  { id: 'unique_15', name: 'Variety Pack 15', description: 'Log 15 different types of exercises', icon: 'Medal' },
  { id: 'unique_20', name: 'Variety Pack 20', description: 'Log 20 different types of exercises', icon: 'Medal' },
  { id: 'session_60', name: 'Endurance 60', description: 'Log a single activity of 60+ minutes', icon: 'Trophy' },
  { id: 'session_90', name: 'Endurance 90', description: 'Log a single activity of 90+ minutes', icon: 'Trophy' },
  { id: 'session_120', name: 'Endurance 120', description: 'Log a single activity of 120+ minutes', icon: 'Trophy' },
  { id: 'session_180', name: 'Endurance 180', description: 'Log a single activity of 180+ minutes', icon: 'Trophy' },
  { id: 'session_240', name: 'Endurance 240', description: 'Log a single activity of 240+ minutes', icon: 'Trophy' },
  { id: 'session_300', name: 'Endurance 300', description: 'Log a single activity of 300+ minutes', icon: 'Trophy' },
  { id: 'streak_3', name: 'Streak 3', description: 'Log activities 3 days in a row', icon: 'Flame' },
  { id: 'streak_7', name: 'Streak 7', description: 'Log activities 7 days in a row', icon: 'Flame' },
  { id: 'streak_14', name: 'Streak 14', description: 'Log activities 14 days in a row', icon: 'Flame' },
  { id: 'streak_30', name: 'Streak 30', description: 'Log activities 30 days in a row', icon: 'Flame' },
  { id: 'streak_60', name: 'Streak 60', description: 'Log activities 60 days in a row', icon: 'Flame' },
  { id: 'streak_100', name: 'Streak 100', description: 'Log activities 100 days in a row', icon: 'Flame' },
  { id: 'streak_200', name: 'Streak 200', description: 'Log activities 200 days in a row', icon: 'Flame' },
  { id: 'streak_365', name: 'Streak 365', description: 'Log activities 365 days in a row', icon: 'Flame' },
  { id: 'ex_brisk_walking_1', name: 'Brisk Walking Fanatic 1', description: 'Log Brisk Walking 1 times', icon: 'Star' },
  { id: 'ex_brisk_walking_5', name: 'Brisk Walking Fanatic 5', description: 'Log Brisk Walking 5 times', icon: 'Star' },
  { id: 'ex_brisk_walking_20', name: 'Brisk Walking Fanatic 20', description: 'Log Brisk Walking 20 times', icon: 'Star' },
  { id: 'ex_brisk_walking_50', name: 'Brisk Walking Fanatic 50', description: 'Log Brisk Walking 50 times', icon: 'Star' },
  { id: 'ex_brisk_walking_100', name: 'Brisk Walking Fanatic 100', description: 'Log Brisk Walking 100 times', icon: 'Star' },
  { id: 'ex_gentle_yoga_1', name: 'Gentle Yoga Fanatic 1', description: 'Log Gentle Yoga 1 times', icon: 'Star' },
  { id: 'ex_gentle_yoga_5', name: 'Gentle Yoga Fanatic 5', description: 'Log Gentle Yoga 5 times', icon: 'Star' },
  { id: 'ex_gentle_yoga_20', name: 'Gentle Yoga Fanatic 20', description: 'Log Gentle Yoga 20 times', icon: 'Star' },
  { id: 'ex_gentle_yoga_50', name: 'Gentle Yoga Fanatic 50', description: 'Log Gentle Yoga 50 times', icon: 'Star' },
  { id: 'ex_gentle_yoga_100', name: 'Gentle Yoga Fanatic 100', description: 'Log Gentle Yoga 100 times', icon: 'Star' },
  { id: 'ex_swimming_1', name: 'Swimming Fanatic 1', description: 'Log Swimming 1 times', icon: 'Star' },
  { id: 'ex_swimming_5', name: 'Swimming Fanatic 5', description: 'Log Swimming 5 times', icon: 'Star' },
  { id: 'ex_swimming_20', name: 'Swimming Fanatic 20', description: 'Log Swimming 20 times', icon: 'Star' },
  { id: 'ex_swimming_50', name: 'Swimming Fanatic 50', description: 'Log Swimming 50 times', icon: 'Star' },
  { id: 'ex_swimming_100', name: 'Swimming Fanatic 100', description: 'Log Swimming 100 times', icon: 'Star' },
  { id: 'ex_chair_aerobics_1', name: 'Chair Aerobics Fanatic 1', description: 'Log Chair Aerobics 1 times', icon: 'Star' },
  { id: 'ex_chair_aerobics_5', name: 'Chair Aerobics Fanatic 5', description: 'Log Chair Aerobics 5 times', icon: 'Star' },
  { id: 'ex_chair_aerobics_20', name: 'Chair Aerobics Fanatic 20', description: 'Log Chair Aerobics 20 times', icon: 'Star' },
  { id: 'ex_chair_aerobics_50', name: 'Chair Aerobics Fanatic 50', description: 'Log Chair Aerobics 50 times', icon: 'Star' },
  { id: 'ex_chair_aerobics_100', name: 'Chair Aerobics Fanatic 100', description: 'Log Chair Aerobics 100 times', icon: 'Star' },
  { id: 'ex_resistance_band_training_1', name: 'Resistance Band Training Fanatic 1', description: 'Log Resistance Band Training 1 times', icon: 'Star' },
  { id: 'ex_resistance_band_training_5', name: 'Resistance Band Training Fanatic 5', description: 'Log Resistance Band Training 5 times', icon: 'Star' },
  { id: 'ex_resistance_band_training_20', name: 'Resistance Band Training Fanatic 20', description: 'Log Resistance Band Training 20 times', icon: 'Star' },
  { id: 'ex_resistance_band_training_50', name: 'Resistance Band Training Fanatic 50', description: 'Log Resistance Band Training 50 times', icon: 'Star' },
  { id: 'ex_resistance_band_training_100', name: 'Resistance Band Training Fanatic 100', description: 'Log Resistance Band Training 100 times', icon: 'Star' },
  { id: 'ex_tai_chi_1', name: 'Tai Chi Fanatic 1', description: 'Log Tai Chi 1 times', icon: 'Star' },
  { id: 'ex_tai_chi_5', name: 'Tai Chi Fanatic 5', description: 'Log Tai Chi 5 times', icon: 'Star' },
  { id: 'ex_tai_chi_20', name: 'Tai Chi Fanatic 20', description: 'Log Tai Chi 20 times', icon: 'Star' },
  { id: 'ex_tai_chi_50', name: 'Tai Chi Fanatic 50', description: 'Log Tai Chi 50 times', icon: 'Star' },
  { id: 'ex_tai_chi_100', name: 'Tai Chi Fanatic 100', description: 'Log Tai Chi 100 times', icon: 'Star' },
  { id: 'ex_bodyweight_squats_1', name: 'Bodyweight Squats Fanatic 1', description: 'Log Bodyweight Squats 1 times', icon: 'Star' },
  { id: 'ex_bodyweight_squats_5', name: 'Bodyweight Squats Fanatic 5', description: 'Log Bodyweight Squats 5 times', icon: 'Star' },
  { id: 'ex_bodyweight_squats_20', name: 'Bodyweight Squats Fanatic 20', description: 'Log Bodyweight Squats 20 times', icon: 'Star' },
  { id: 'ex_bodyweight_squats_50', name: 'Bodyweight Squats Fanatic 50', description: 'Log Bodyweight Squats 50 times', icon: 'Star' },
  { id: 'ex_bodyweight_squats_100', name: 'Bodyweight Squats Fanatic 100', description: 'Log Bodyweight Squats 100 times', icon: 'Star' },
  { id: 'ex_stretching_routine_1', name: 'Stretching Routine Fanatic 1', description: 'Log Stretching Routine 1 times', icon: 'Star' },
  { id: 'ex_stretching_routine_5', name: 'Stretching Routine Fanatic 5', description: 'Log Stretching Routine 5 times', icon: 'Star' },
  { id: 'ex_stretching_routine_20', name: 'Stretching Routine Fanatic 20', description: 'Log Stretching Routine 20 times', icon: 'Star' },
  { id: 'ex_stretching_routine_50', name: 'Stretching Routine Fanatic 50', description: 'Log Stretching Routine 50 times', icon: 'Star' },
  { id: 'ex_stretching_routine_100', name: 'Stretching Routine Fanatic 100', description: 'Log Stretching Routine 100 times', icon: 'Star' },
  { id: 'ex_dancing_1', name: 'Dancing Fanatic 1', description: 'Log Dancing 1 times', icon: 'Star' },
  { id: 'ex_dancing_5', name: 'Dancing Fanatic 5', description: 'Log Dancing 5 times', icon: 'Star' },
  { id: 'ex_dancing_20', name: 'Dancing Fanatic 20', description: 'Log Dancing 20 times', icon: 'Star' },
  { id: 'ex_dancing_50', name: 'Dancing Fanatic 50', description: 'Log Dancing 50 times', icon: 'Star' },
  { id: 'ex_dancing_100', name: 'Dancing Fanatic 100', description: 'Log Dancing 100 times', icon: 'Star' },
  { id: 'ex_pilates_1', name: 'Pilates Fanatic 1', description: 'Log Pilates 1 times', icon: 'Star' },
  { id: 'ex_pilates_5', name: 'Pilates Fanatic 5', description: 'Log Pilates 5 times', icon: 'Star' },
  { id: 'ex_pilates_20', name: 'Pilates Fanatic 20', description: 'Log Pilates 20 times', icon: 'Star' },
  { id: 'ex_pilates_50', name: 'Pilates Fanatic 50', description: 'Log Pilates 50 times', icon: 'Star' },
  { id: 'ex_pilates_100', name: 'Pilates Fanatic 100', description: 'Log Pilates 100 times', icon: 'Star' },
  { id: 'ex_heavy_lifting_1', name: 'Heavy Lifting Fanatic 1', description: 'Log Heavy Lifting 1 times', icon: 'Star' },
  { id: 'ex_heavy_lifting_5', name: 'Heavy Lifting Fanatic 5', description: 'Log Heavy Lifting 5 times', icon: 'Star' },
  { id: 'ex_heavy_lifting_20', name: 'Heavy Lifting Fanatic 20', description: 'Log Heavy Lifting 20 times', icon: 'Star' },
  { id: 'ex_heavy_lifting_50', name: 'Heavy Lifting Fanatic 50', description: 'Log Heavy Lifting 50 times', icon: 'Star' },
  { id: 'ex_heavy_lifting_100', name: 'Heavy Lifting Fanatic 100', description: 'Log Heavy Lifting 100 times', icon: 'Star' },
  { id: 'weekend_1', name: 'Weekend Warrior 1', description: 'Log 1 weekend activities', icon: 'Medal' },
  { id: 'weekend_5', name: 'Weekend Warrior 5', description: 'Log 5 weekend activities', icon: 'Medal' },
  { id: 'weekend_20', name: 'Weekend Warrior 20', description: 'Log 20 weekend activities', icon: 'Medal' },
  { id: 'weekend_50', name: 'Weekend Warrior 50', description: 'Log 50 weekend activities', icon: 'Medal' },
  { id: 'weekend_100', name: 'Weekend Warrior 100', description: 'Log 100 weekend activities', icon: 'Medal' },
  { id: 'first_step', name: 'First Step', description: 'Log your first activity', icon: 'Star' },
  { id: 'getting_serious', name: 'Getting Serious', description: 'Log 5 total activities', icon: 'Medal' },
  { id: 'century_club', name: 'Century Club', description: 'Reach 100 active minutes', icon: 'Award' },
  { id: 'marathoner', name: 'Marathoner', description: 'Reach 500 active minutes', icon: 'Trophy' }
];

const achMap = Object.fromEntries(ALL_ACHIEVEMENTS.map(a => [a.id, a]));

export function evaluateAchievements(logs: ActivityLog[]): Achievement[] {
  const count = logs.length;
  const dur = logs.reduce((sum, doc) => sum + doc.duration, 0);
  const uniqueExercises = new Set(logs.map(l => l.exercise_name)).size;
  const maxSession = logs.reduce((max, l) => Math.max(max, l.duration), 0);
  
  const exerciseCounts: Record<string, number> = {};
  logs.forEach(l => {
    exerciseCounts[l.exercise_name] = (exerciseCounts[l.exercise_name] || 0) + 1;
  });

  const weekendCount = logs.filter(l => {
    const [y, m, d] = l.date.split('-').map(Number);
    const dayOfWeek = new Date(y, m - 1, d).getDay();
    return dayOfWeek === 0 || dayOfWeek === 6;
  }).length;

  const uniqueDates = Array.from(new Set(logs.map(l => l.date))).sort();
  let maxStreak = 0;
  let curStr = 0;
  for (let i = 0; i < uniqueDates.length; i++) {
    if (i === 0) curStr = 1;
    else {
      const [y1, m1, d1] = uniqueDates[i-1].split('-').map(Number);
      const [y2, m2, d2] = uniqueDates[i].split('-').map(Number);
      const diffDays = Math.round((new Date(y2, m2 - 1, d2).getTime() - new Date(y1, m1 - 1, d1).getTime()) / (1000 * 3600 * 24));
      if (diffDays === 1) curStr++;
      else curStr = 1;
    }
    maxStreak = Math.max(maxStreak, curStr);
  }

  const unlocked: Achievement[] = [];
  if (count >= 1) unlocked.push(achMap['count_1']);
  if (count >= 5) unlocked.push(achMap['count_5']);
  if (count >= 10) unlocked.push(achMap['count_10']);
  if (count >= 25) unlocked.push(achMap['count_25']);
  if (count >= 50) unlocked.push(achMap['count_50']);
  if (count >= 100) unlocked.push(achMap['count_100']);
  if (count >= 250) unlocked.push(achMap['count_250']);
  if (count >= 500) unlocked.push(achMap['count_500']);
  if (count >= 1000) unlocked.push(achMap['count_1000']);
  if (count >= 2000) unlocked.push(achMap['count_2000']);
  if (dur >= 50) unlocked.push(achMap['min_50']);
  if (dur >= 100) unlocked.push(achMap['min_100']);
  if (dur >= 500) unlocked.push(achMap['min_500']);
  if (dur >= 1000) unlocked.push(achMap['min_1000']);
  if (dur >= 2500) unlocked.push(achMap['min_2500']);
  if (dur >= 5000) unlocked.push(achMap['min_5000']);
  if (dur >= 10000) unlocked.push(achMap['min_10000']);
  if (dur >= 25000) unlocked.push(achMap['min_25000']);
  if (dur >= 50000) unlocked.push(achMap['min_50000']);
  if (dur >= 100000) unlocked.push(achMap['min_100000']);
  if (uniqueExercises >= 3) unlocked.push(achMap['unique_3']);
  if (uniqueExercises >= 5) unlocked.push(achMap['unique_5']);
  if (uniqueExercises >= 10) unlocked.push(achMap['unique_10']);
  if (uniqueExercises >= 15) unlocked.push(achMap['unique_15']);
  if (uniqueExercises >= 20) unlocked.push(achMap['unique_20']);
  if (maxSession >= 60) unlocked.push(achMap['session_60']);
  if (maxSession >= 90) unlocked.push(achMap['session_90']);
  if (maxSession >= 120) unlocked.push(achMap['session_120']);
  if (maxSession >= 180) unlocked.push(achMap['session_180']);
  if (maxSession >= 240) unlocked.push(achMap['session_240']);
  if (maxSession >= 300) unlocked.push(achMap['session_300']);
  if (maxStreak >= 3) unlocked.push(achMap['streak_3']);
  if (maxStreak >= 7) unlocked.push(achMap['streak_7']);
  if (maxStreak >= 14) unlocked.push(achMap['streak_14']);
  if (maxStreak >= 30) unlocked.push(achMap['streak_30']);
  if (maxStreak >= 60) unlocked.push(achMap['streak_60']);
  if (maxStreak >= 100) unlocked.push(achMap['streak_100']);
  if (maxStreak >= 200) unlocked.push(achMap['streak_200']);
  if (maxStreak >= 365) unlocked.push(achMap['streak_365']);
  if ((exerciseCounts['Brisk Walking'] || 0) >= 1) unlocked.push(achMap['ex_brisk_walking_1']);
  if ((exerciseCounts['Brisk Walking'] || 0) >= 5) unlocked.push(achMap['ex_brisk_walking_5']);
  if ((exerciseCounts['Brisk Walking'] || 0) >= 20) unlocked.push(achMap['ex_brisk_walking_20']);
  if ((exerciseCounts['Brisk Walking'] || 0) >= 50) unlocked.push(achMap['ex_brisk_walking_50']);
  if ((exerciseCounts['Brisk Walking'] || 0) >= 100) unlocked.push(achMap['ex_brisk_walking_100']);
  if ((exerciseCounts['Gentle Yoga'] || 0) >= 1) unlocked.push(achMap['ex_gentle_yoga_1']);
  if ((exerciseCounts['Gentle Yoga'] || 0) >= 5) unlocked.push(achMap['ex_gentle_yoga_5']);
  if ((exerciseCounts['Gentle Yoga'] || 0) >= 20) unlocked.push(achMap['ex_gentle_yoga_20']);
  if ((exerciseCounts['Gentle Yoga'] || 0) >= 50) unlocked.push(achMap['ex_gentle_yoga_50']);
  if ((exerciseCounts['Gentle Yoga'] || 0) >= 100) unlocked.push(achMap['ex_gentle_yoga_100']);
  if ((exerciseCounts['Swimming'] || 0) >= 1) unlocked.push(achMap['ex_swimming_1']);
  if ((exerciseCounts['Swimming'] || 0) >= 5) unlocked.push(achMap['ex_swimming_5']);
  if ((exerciseCounts['Swimming'] || 0) >= 20) unlocked.push(achMap['ex_swimming_20']);
  if ((exerciseCounts['Swimming'] || 0) >= 50) unlocked.push(achMap['ex_swimming_50']);
  if ((exerciseCounts['Swimming'] || 0) >= 100) unlocked.push(achMap['ex_swimming_100']);
  if ((exerciseCounts['Chair Aerobics'] || 0) >= 1) unlocked.push(achMap['ex_chair_aerobics_1']);
  if ((exerciseCounts['Chair Aerobics'] || 0) >= 5) unlocked.push(achMap['ex_chair_aerobics_5']);
  if ((exerciseCounts['Chair Aerobics'] || 0) >= 20) unlocked.push(achMap['ex_chair_aerobics_20']);
  if ((exerciseCounts['Chair Aerobics'] || 0) >= 50) unlocked.push(achMap['ex_chair_aerobics_50']);
  if ((exerciseCounts['Chair Aerobics'] || 0) >= 100) unlocked.push(achMap['ex_chair_aerobics_100']);
  if ((exerciseCounts['Resistance Band Training'] || 0) >= 1) unlocked.push(achMap['ex_resistance_band_training_1']);
  if ((exerciseCounts['Resistance Band Training'] || 0) >= 5) unlocked.push(achMap['ex_resistance_band_training_5']);
  if ((exerciseCounts['Resistance Band Training'] || 0) >= 20) unlocked.push(achMap['ex_resistance_band_training_20']);
  if ((exerciseCounts['Resistance Band Training'] || 0) >= 50) unlocked.push(achMap['ex_resistance_band_training_50']);
  if ((exerciseCounts['Resistance Band Training'] || 0) >= 100) unlocked.push(achMap['ex_resistance_band_training_100']);
  if ((exerciseCounts['Tai Chi'] || 0) >= 1) unlocked.push(achMap['ex_tai_chi_1']);
  if ((exerciseCounts['Tai Chi'] || 0) >= 5) unlocked.push(achMap['ex_tai_chi_5']);
  if ((exerciseCounts['Tai Chi'] || 0) >= 20) unlocked.push(achMap['ex_tai_chi_20']);
  if ((exerciseCounts['Tai Chi'] || 0) >= 50) unlocked.push(achMap['ex_tai_chi_50']);
  if ((exerciseCounts['Tai Chi'] || 0) >= 100) unlocked.push(achMap['ex_tai_chi_100']);
  if ((exerciseCounts['Bodyweight Squats'] || 0) >= 1) unlocked.push(achMap['ex_bodyweight_squats_1']);
  if ((exerciseCounts['Bodyweight Squats'] || 0) >= 5) unlocked.push(achMap['ex_bodyweight_squats_5']);
  if ((exerciseCounts['Bodyweight Squats'] || 0) >= 20) unlocked.push(achMap['ex_bodyweight_squats_20']);
  if ((exerciseCounts['Bodyweight Squats'] || 0) >= 50) unlocked.push(achMap['ex_bodyweight_squats_50']);
  if ((exerciseCounts['Bodyweight Squats'] || 0) >= 100) unlocked.push(achMap['ex_bodyweight_squats_100']);
  if ((exerciseCounts['Stretching Routine'] || 0) >= 1) unlocked.push(achMap['ex_stretching_routine_1']);
  if ((exerciseCounts['Stretching Routine'] || 0) >= 5) unlocked.push(achMap['ex_stretching_routine_5']);
  if ((exerciseCounts['Stretching Routine'] || 0) >= 20) unlocked.push(achMap['ex_stretching_routine_20']);
  if ((exerciseCounts['Stretching Routine'] || 0) >= 50) unlocked.push(achMap['ex_stretching_routine_50']);
  if ((exerciseCounts['Stretching Routine'] || 0) >= 100) unlocked.push(achMap['ex_stretching_routine_100']);
  if ((exerciseCounts['Dancing'] || 0) >= 1) unlocked.push(achMap['ex_dancing_1']);
  if ((exerciseCounts['Dancing'] || 0) >= 5) unlocked.push(achMap['ex_dancing_5']);
  if ((exerciseCounts['Dancing'] || 0) >= 20) unlocked.push(achMap['ex_dancing_20']);
  if ((exerciseCounts['Dancing'] || 0) >= 50) unlocked.push(achMap['ex_dancing_50']);
  if ((exerciseCounts['Dancing'] || 0) >= 100) unlocked.push(achMap['ex_dancing_100']);
  if ((exerciseCounts['Pilates'] || 0) >= 1) unlocked.push(achMap['ex_pilates_1']);
  if ((exerciseCounts['Pilates'] || 0) >= 5) unlocked.push(achMap['ex_pilates_5']);
  if ((exerciseCounts['Pilates'] || 0) >= 20) unlocked.push(achMap['ex_pilates_20']);
  if ((exerciseCounts['Pilates'] || 0) >= 50) unlocked.push(achMap['ex_pilates_50']);
  if ((exerciseCounts['Pilates'] || 0) >= 100) unlocked.push(achMap['ex_pilates_100']);
  if ((exerciseCounts['Heavy Lifting'] || 0) >= 1) unlocked.push(achMap['ex_heavy_lifting_1']);
  if ((exerciseCounts['Heavy Lifting'] || 0) >= 5) unlocked.push(achMap['ex_heavy_lifting_5']);
  if ((exerciseCounts['Heavy Lifting'] || 0) >= 20) unlocked.push(achMap['ex_heavy_lifting_20']);
  if ((exerciseCounts['Heavy Lifting'] || 0) >= 50) unlocked.push(achMap['ex_heavy_lifting_50']);
  if ((exerciseCounts['Heavy Lifting'] || 0) >= 100) unlocked.push(achMap['ex_heavy_lifting_100']);
  if (weekendCount >= 1) unlocked.push(achMap['weekend_1']);
  if (weekendCount >= 5) unlocked.push(achMap['weekend_5']);
  if (weekendCount >= 20) unlocked.push(achMap['weekend_20']);
  if (weekendCount >= 50) unlocked.push(achMap['weekend_50']);
  if (weekendCount >= 100) unlocked.push(achMap['weekend_100']);
  if (count >= 1) unlocked.push(achMap['first_step']);
  if (count >= 5) unlocked.push(achMap['getting_serious']);
  if (dur >= 100) unlocked.push(achMap['century_club']);
  if (dur >= 500) unlocked.push(achMap['marathoner']);

  return unlocked;
}
